workflow:
  rules:
    # To avoid running too many pipelines, restrict the times we run one:

    # Run pipelines triggered by a merge request creation/update
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    # Run for pushes to a branch *except* if there is also a merge request for
    # it.
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - single

build_and_test:
  stage: single
  services:
    - image:sandbox
    - cpu:8
    - mem:16
  script:
    - require_issue
    - generic_anod_ci
    - . /tmp/ci_env.sh
    # As long as the imported testsuite is not clean, we should not exercise it
    # in the CI in order to avoid false positives.
    - anod test prettier-ada -Qno-imported
    - testsuite_reports
  artifacts:
    reports:
      junit: xunit-*.xml
